apiVersion: v1
kind: Service
metadata:
  labels:
    app: hotdog
  name: hotdog-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: hotdog
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hotdog-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hotdog-service
                port:
                  number: 80
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: hotdog-hc-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 80
    type: HTTP
    requestPath: /
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hotdog-hpa
  namespace: default
spec:
  scaleTargetRef: # ここでautoscale対象となる`scaled resource object`を指定
    apiVersion: apps/v1
    kind: Deployment
    name: hotdog
  minReplicas: 1 # 最小レプリカ数
  maxReplicas: 10 # 最大レプリカ数
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60 # CPU使用率が常に70%になるように指定